### ISSUE TITLE
点击用户进入用户信息页面失败

### ISSUE THREAD

**Issue by ghost** [heikehuan/fly4j#1]
这个url      http://127.0.0.1:8080/user/home.html

**Comment by ghost** [comment]
404 not found

**Comment by keepmoving1573** [comment]
这个项目刚开始做，home页还没开发完。等我发布1.0稳定版本，最基础功能就能用了。

**Comment by ghost** [comment]
这是你自己的项目吗？

**Comment by keepmoving1573** [comment]
对，后台自己写，前端模板用的开源的flyui

**Comment by ghost** [comment]
您现在主要做这个开发吗？每天都有提交？

**Comment by keepmoving1573** [comment]
这就是个业余项目，练练手而已，有时间就做，没时间就不做。我另外一个项目已经完工了，你可以看一下https://github.com/heikehuan/huanhuan-blog

**Comment by ghost** [comment]
你有没有语音问答方面的代码？顺便留一个微信？

**Comment by keepmoving1573** [comment]
没做过语音
